### ISSUE TITLE
Framework 

### ISSUE THREAD

**Issue by asampath123** [airavata-courses/TeamNPcomplete#2]
I was looking at Grails Framework and its looks good. Its light weight and groovy based web application framework. Groovy is based on java platform. Let me know what you guys think of this or other frameworks you guys are looking at ?

**Comment by pbheemag** [comment]
I was planning to use Jersey framework for RESTful web services , MongoDB for backend and any of angular, react or node js to display the data.

**Comment by kedargn** [comment]
Jersey sounds good. Let's good ahead with it.
