### ISSUE TITLE
Python Framework

### ISSUE THREAD

**Issue by kedargn** [airavata-courses/TeamNPcomplete#3]
We have 3 choices in Python frameworks
1)Django
2)Flask
3)Bottle

What we need is a micro framework. So we can rule out Django as it is not a micro framework. Between Flask and Bottle, Flask supports REST better than Bottle. So, I prefer Flask over Bottle.

Let me know your views.

**Comment by asampath123** [comment]
We will go ahead with Flask. I was reading about it, looks like it is the best among our options.
